Config.hs: Corrects git repo name
typelead/etlas pull request #33
Opened 2018-02-17 08:58 UTC by ouromoros

Closes https://github.com/typelead/eta/issues/634

2018-02-17 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/typelead/etlas?pullRequest=33) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/typelead/etlas?pullRequest=33) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/typelead/etlas?pullRequest=33) it.</sub>

2018-02-17 10:52 UTC, rahulmutt requested changes
Unfortunately, changing the value of `etlasName` would affect the generated directory structure - a folder called `~/.etlas/packages/git@github.com/typelead/eta-index/` would be created according to the current logic.

Rather than changing it at the root, it needs to be changed at the point where the output is displayed to the user. First, check if the repo is git-indexed, in which case the repoUri should be displayed instead of the repoName.

2018-02-18 02:16 UTC, ouromoros commented
@rahulmutt Plz review. I think I have managed it, but I'm not quite sure if I'm doing it the right way. btw, is there anyway to write test for it? Or should I just rebuild manually after a change?

2018-02-18 08:02 UTC, rahulmutt requested changes
@ouromoros Awesome! Your new changes are closer to what I had in mind. I added some comments. Please take care of the changes I suggested.

For now, no need for tests - just rebuild.

2018-02-18 08:02 UTC, rahulmutt commented on etlas/Distribution/Client/Update.hs
> +        | Just (URIAuth "" "github.com" "") == (uriAuthority uri) =
Instead of pattern matching on the URI, you can use the `remoteRepoGitIndexed` field to check if it's a Git-backed index.

2018-02-18 14:57 UTC, ouromoros commented
@rahulmutt Thanks a lot! I made the corresponding change now.
I tried to use a $ and then . operator between the uriPath and remoteRepoURI function to avoid parenthesis, but curiously neither compiled successfully. I'm still very new on Haskell, so could you tell me where I got wrong?

2018-02-18 16:25 UTC, rahulmutt commented
@ouromoros The `$` and `.` don't work properly in the presence of infix operators (in this case (`++`)), so you need to specify parentheses.

What you could've done:
`"git@github.com" ++ (uriPath . remoteRepoURI $ repo)`
OR
`"git@github.com" ++ (uriPath $ remoteRepoURI repo)`

IMHO, neither of these is any clearer than just using simple parentheses like you've done in your PR. In small expressions like this, I prefer not to use `$` and `.` since they make it look unnecessarily complicated. `$` and `.` are great for large pipelines of functions or when the number of parenthesis become unwieldly (say 3 layers of parens)..

A quick way to remember how it works:

`(a . b. c . d) $ e = (a . b . c) $ d e = (a . b) $ c (d e) = a (b (c (d e))`

2018-02-18 16:25 UTC, rahulmutt approved these changes
Great stuff @ouromoros! Merging.

2018-02-18 16:25 UTC, merged